### ISSUE TITLE
Use of deprecated node version

### ISSUE THREAD

**Issue by Kopfstein** [jdno/setup-butler#386]
Using the action gives following deprecation warning:

```
The following actions use a deprecated Node.js version and will be forced to run on node20: jdno/setup-butler@v1. 
For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
```

**Comment by jdno** [comment]
Thanks for reporting this! I've just releases [1.5.0](https://github.com/jdno/setup-butler/releases/tag/v1.5.0), which bumps the runtime version to `node20` and should fix this.
